/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    gradlePluginPortal()
    mavenCentral()
    google()
}

dependencies {
//    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin")
//    implementation("com.android.tools.build:gradle:7.1.1")
//    implementation("com.google.devtools.ksp:symbol-processing-gradle-plugin:1.6.10-1.0.2")
}
